name: EROS images
favicon: null
layout_spectrum: 0.8557862010784447
typography_spectrum: 0.8356731997337192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070809'
    - '#411a17'
    - '#6e3024'
    - '#a66327'
    - '#d39760'
  brandStrength: 0.375
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
